name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load environment vars
        run: BRANCH=${GITHUB_REF#refs/heads/} cat build/$BRANCH.env >> $GITHUB_ENV

      - name: Test something
        run: |
          echo Deploy URL is ${{ env.DEPLOY_URL }}
          echo Test = ${{ env.TEST }}
