name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current branch name
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Test something
        run: |
          source build/${{ env.BRANCH }}.env
          echo $DEPLOY_URL
